### ISSUE TITLE
Not a running Demo Code

### ISSUE THREAD

**Issue by akashqss** [nubomedia-vtt/kurento-room-client-android#3] opened 2016-08-05 07:40 UTC
Please help to create a demo app for android with your library.

**Comment by jpsjanne** [comment] 2016-08-05 07:49
You can find a demo app for android in 
https://github.com/nubomedia-vtt/nubo-test

That project demonstrates a simple chat room app where users can also initiate p2p video calls. You will need to have a Kurento room server set up:
https://github.com/Kurento/kurento-room

For more help, please refer to these documents as well as javadocs in the project files:
http://webrtcpeer-android.readthedocs.io/en/latest/
http://kurento-room-client-android.readthedocs.io/en/latest/

**Comment by akashqss** [comment] 2016-08-05 09:29
I am using your code. It is for p2p call but i want to make a video conference using Kurento room. We have setup kurento room and this is work for IOs but when I am trying your code its not worked.

**Comment by jpsjanne** [comment] 2016-08-05 09:32
I'm afraid you'll have to be a bit more specific. Can you give me some information on where the problems arise?

**Comment by akashqss** [comment] 2016-08-05 09:36
I have setup URL of Kurento room server in setting. When I want to call a person who are already in room it always show Publishing....

**Comment by jpsjanne** [comment] 2016-08-05 10:06
Please start by pulling the latest version of nubo-test, I pushed some updates just now.

I confirmed with the latest versions that my own test bed works as expected. Do you see any errors or exceptions (in Android Monitor or similar debug handle)? If so, please post them in here and I'll see what I can do. If not, can you confirm if you see an info log message "PeerVideoActivity initialized"?

**Comment by akashqss** [comment] 2016-08-05 10:25
Hello I am getting this issue.

08-05 15:54:15.960 818-818/fi.vtt.nubotest W/System.err:    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
08-05 15:54:15.960 818-818/fi.vtt.nubotest E/rtc: #
                                                  # Fatal error in ../../talk/app/webrtc/java/jni/classreferenceholder.cc, line 136
                                                  # Check failed: !jni->ExceptionCheck()
                                                  # error during FindClass: org/webrtc/MediaCodecVideoDecoder$DecoderOutputBufferInfo
                                                  #3 

and also gate this 

```
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

my server url is https.

**Comment by jpsjanne** [comment] 2016-08-05 10:40
Looks like you app has some trouble loading the native code of Libjingle. The first thing would be to verify that when you build the app that the
nubo-test\app\build\intermediates\exploded-aar\io.pristine\libjingle\11139
contains folders arm64-v8a and armeabi-v7a, and that both contain file libjingle_peerconnection_so.so. Could you also tell me what Android versions you are using, and what is your development environment and its version as well?

**Comment by akashqss** [comment] 2016-08-05 10:43
I have only  armeabi-v7a folder with libjingle_peerconnection_so.so and My device version is 6.0 and My android studio version is 2.1

Can I create a folder with  arm64-v8a name and put ibjingle_peerconnection_so.so file in that?

**Comment by jpsjanne** [comment] 2016-08-05 10:56
Very good. I have never tested this software on Android 6, but my rough guess is that you want to have Libjingle compiled to arm64-v8a to make it work. Please open Android SDK Manager and check that all items with "ARM 64" in the name are installed. You may also have to tweak some other settings, but I am unfamiliar with this process and unfortunately cannot help you more. When you manage to compile the arm64-v8a of libjingle_peerconnection_so.so, let me know if it solved the problem.

**Comment by jpsjanne** [comment] 2016-08-29 09:10
This issue got resolved in 
[https://github.com/nubomedia-vtt/webrtcpeer-android/issues/2](url)

Please pull a new revision of nubo-test

**Closed as completed by jpsjanne** 2016-08-29 09:10 UTC

**Comment by Hassan99** [comment] 2017-02-27 11:21
I am having this kind of URL , https://mydomain.com/provider/wc/?room=86847535&pin=891411#                  now how to use the url for mobile application. ? when i connect on the MainActivity in your demo app, the error dialog shown with the message of " You have been disconnected from room" but , in my domain, web application works fine. How to solve this issue.?those docs url saying permission denied error even i signed up.

**Comment by jpsjanne** [comment] 2017-02-28 07:53
Hello Hassan,

The documentation URLs are outdated, and the new ones are as follows. You should not need to sign up to read documentation.
http://doc-webrtcpeer-android.readthedocs.io/en/latest/
http://doc-kurento-room-client-android.readthedocs.io/en/latest/

Could you please post your request to our Google development group, it's a much better place in receiving help for development. Issues should be only raised when there is something specific related to the library, and this issue has already closed in any case.
https://groups.google.com/forum/#!forum/nubomedia-dev

You should also post some debug information. The first thing I would suggest that you double-check that your certificate is properly installed. There is also an issue with Android 5.0.x versions:
http://doc-kurento-room-client-android.readthedocs.io/en/latest/DevelopersGuide.html#wss-support-on-android-5-0-x-lollipop-and-up

**Comment by aditya6992** [comment] 2017-08-31 14:41
in the nubo-test app, as I understand it, there is no way to add ice/stun/turn server configurations, is this right?

**Comment by sudhir-vaghasiya** [comment] 2019-10-01 03:49
Hello Janne Seppänen

I have problem with android app.

I connect room using android app then my audio and video streaming working perfect in Web Version but same way i am not able to streaming in android app
